"""Seed table risk_estimation_models

Revision ID: 367698e9203e
Revises: c758bf8edb6b
Create Date: 2025-11-24 13:30:56.149585

"""
from datetime import datetime
from typing import Sequence, Union
from uuid import uuid4

from alembic import op
import sqlalchemy as sa

from src.db.constants.risk_db_constants import RiskDbConstants

# revision identifiers, used by Alembic.
revision: str = '367698e9203e'
down_revision: Union[str, Sequence[str], None] = 'c758bf8edb6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    risk_estimation_models = sa.table(
        'risk_estimation_models',
        sa.column('id', sa.UUID),
        sa.column('created_at', sa.DateTime),
        sa.column('name', sa.String),
        sa.column('description', sa.String),
        sa.column('reference', sa.String)
    )
    op.bulk_insert(
        risk_estimation_models,
        [
            {
                "id": uuid4(),
                "created_at": datetime.now(),
                "name": "Baseline risk assessment model",
                "description": "Baseline risk assessment model",
                "reference": RiskDbConstants.RISK_ESTIMATION_MODEL_REF_BASELINE
            },
        ]
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
