"""Create tables - alerts, alert_types, alert_sending_statuses, alert_severities, alert_types, risk_estimation_models

Revision ID: 5e35f8c8870e
Revises: 
Create Date: 2025-11-24 12:41:04.333022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e35f8c8870e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_sending_statuses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('reference', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('alert_severities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('reference', sa.String(length=80), nullable=False),
    sa.Column('max_risk_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index('idx0_alert_severities_max_risk_score', 'alert_severities', ['max_risk_score'], unique=False)
    op.create_table('alert_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('reference', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('risk_estimation_models',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('sender', sa.String(length=512), nullable=True),
    sa.Column('recipient', sa.String(length=512), nullable=True),
    sa.Column('severity_id', sa.Uuid(), nullable=False),
    sa.Column('type_id', sa.Uuid(), nullable=False),
    sa.Column('sending_status_id', sa.Uuid(), nullable=False),
    sa.Column('risk_estimation_model_id', sa.Uuid(), nullable=False),
    sa.Column('first_sent_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=True),
    sa.Column('is_batch', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['risk_estimation_model_id'], ['risk_estimation_models.id'], ),
    sa.ForeignKeyConstraint(['sending_status_id'], ['alert_sending_statuses.id'], ),
    sa.ForeignKeyConstraint(['severity_id'], ['alert_severities.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['alert_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx0_alerts_sent_at', 'alerts', ['sent_at'], unique=False)
    op.create_index('idx1_alerts_first_sent_attempt_at', 'alerts', ['first_sent_attempt_at'], unique=False)
    op.create_index('idx2_alerts_subject', 'alerts', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx2_alerts_subject', table_name='alerts')
    op.drop_index('idx1_alerts_first_sent_attempt_at', table_name='alerts')
    op.drop_index('idx0_alerts_sent_at', table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('risk_estimation_models')
    op.drop_table('alert_types')
    op.drop_index('idx0_alert_severities_max_risk_score', table_name='alert_severities')
    op.drop_table('alert_severities')
    op.drop_table('alert_sending_statuses')
    # ### end Alembic commands ###
