"""Seed table alert_sending_statuses

Revision ID: c758bf8edb6b
Revises: c104dfab4758
Create Date: 2025-11-24 13:28:44.635670

"""
from datetime import datetime
from typing import Sequence, Union
from uuid import uuid4

from alembic import op
import sqlalchemy as sa

from src.db.constants.alert_db_constants import AlertDbConstants

# revision identifiers, used by Alembic.
revision: str = 'c758bf8edb6b'
down_revision: Union[str, Sequence[str], None] = 'c104dfab4758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    alert_sending_statuses_table = sa.table(
        'alert_sending_statuses',
        sa.column('id', sa.UUID),
        sa.column('created_at', sa.DateTime),
        sa.column('name', sa.String),
        sa.column('reference', sa.String)
    )
    op.bulk_insert(
        alert_sending_statuses_table,
        [
            {
                "id": uuid4(),
                "created_at": datetime.now(),
                "name": "Pending",
                "reference": AlertDbConstants.ALERT_SENDING_STATUS_REF_PENDING
            },
            {
                "id": uuid4(),
                "created_at": datetime.now(),
                "name": "Error",
                "reference": AlertDbConstants.ALERT_SENDING_STATUS_REF_ERROR
            },
            {
                "id": uuid4(),
                "created_at": datetime.now(),
                "name": "Sent",
                "reference": AlertDbConstants.ALERT_SENDING_STATUS_REF_SENT
            },
        ]
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
